[build]
  command = "npm run build"
  publish = "dist"
  functions = "backend/functions"

[dev]
  command = "npm run dev"
  functions = "backend/functions"
  targetPort = 3000
  port = 8888
  NETLIFY_DEV_LOCAL_ENV = true