export const packageData = [
    {
        id: 1,
        title: "Early Bird",
        price: 1500,
        features: [
            "Up to 5 users",
            "Unlimited projects",
            "Basic analytics",
            "Limited support",
        ],
    },
    {
        id: 2,
        title: "Advanced",
        price: 2500,
        features: [
            "Up to 10 users lorem text is a good thing we belove in niggas eveyrwhere",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
        ],
    },
        {
        id: 3,
        title: "Digga",
        price: 25400,
        features: [
            "Up to 10 users lorem text is a good thing we belove in niggas eveyrwhere",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
            "lorem text is a good thing we belove in niggas eveyrwhere",
              "Priority support",
            "Advanced analytics",
            "Custom branding",
             "Up to 10 users",
            "Priority support",
            "Advanced analytics",
            "Custom branding",
            "lorem text is a good thing we belove in niggas eveyrwhere",
        ],
    },
];
